name: '$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
- dev
- master

pr:
  autoCancel: false
  branches:
    include:
    - '*'

# pool:
#   vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  versionSuffix: 'beta-$(Build.BuildNumber)'

jobs:
- job: 'Linux'
  displayName: 'Build on Ubuntu'
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: |
        src/**/*.csproj
      arguments: '-c Release -f netstandard2.0'
    name: 'Build'
    displayName: 'build sources'

  # TODO: re-work unit tests to run without unpredictable local DNS results or run bind on those build agents?
  # - task: DotNetCoreCLI@2
  #   inputs:
  #     command: 'test'
  #     projects: 'test/DnsClient.Tests/*.csproj'
  #     publishTestResults: true
  #     arguments: '-c Release -f netcoreapp3.0'

- job: Windows
  displayName: 'Build & Test on Windows'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: |
        src/**/*.csproj
        test/DnsClient.Tests/*.csproj
      arguments: '-c Release'
    name: 'Build'
    displayName: 'dotnet build'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: 'test/DnsClient.Tests/*.csproj'
      publishTestResults: true
      arguments: '-c Release --no-build --no-restore'

  - script: 'dotnet pack src\DnsClient\DnsClient.csproj -c Release --no-build --no-restore --version-suffix $(versionSuffix) -v normal -o $(Build.ArtifactStagingDirectory)'
    name: 'PackBeta'
    displayName: 'dotnet pack for beta'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'beta'