name: '$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '1.3.0-beta-$(Build.BuildNumber)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    verbosityRestore: Normal

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'test/DnsClient.Tests/*.csproj'
    publishTestResults: true
    arguments: '-c $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/DnsClient/*.csproj'
    nobuild: true
    includesymbols: true
    versioningScheme: 'off'
    buildProperties: '/p:PackageVersion=$(version)'
    verbosityPack: Normal
    arguments: '-c $(buildConfiguration) --no-build --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'nugets'