name: '$(Date:yyyyMMdd)$(Rev:.r)'

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '1.3.0-beta-$(Build.BuildNumber)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    verbosityRestore: Minimal

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'test/DnsClient.Tests/*.csproj'
    publishTestResults: true
    arguments: '-c $(buildConfiguration) --no-build --no-restore'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/DnsClient/*.csproj'
    includesymbols: false
    versioningScheme: 'off'
    verbosityPack: Minimal
    configuration: '$(buildConfiguration)'
    arguments: '-c $(buildConfiguration) --no-build --no-restore --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(version)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'nugets'